### PR TITLE
Fix small path-reading bug

### PR DESCRIPTION
**Pull request by acsor**
Hi, my reason for submitting this PR is twofold

- For fixing a small bug in the `cli.js` file
- For showing my gratitude toward this project (whoever authored this saved me and my team half a week worth of time)

Out of the many commits only <https://github.com/ruyadorno/twitter-proxy/commit/5b62e263a9526b47ecd37440a05366534c2d9a8c> is a bit opinionated, and you may discard it if there were compelling reasons for having the `proxy/` dir. All the remaining ones are the bug-fixing commit and "soft" commits which do not affect the code semantics. I've also fixed the `npm start` script (hopefully correctly).

### CODE REVIEW

**Comment by ruyadorno** [comment]
Awesome! 👍 LGTM

**Comment by ruyadorno** [comment]
Thanks for taking the time @acsor 😄 Published as `v2.0.1`

**Comment by acsor** [comment]
Hi, thanks a lot for the quick reply! I'm afraid I overlooked one small detail in the run instructions of `README.md` for those who clone the repo, as one also needs to type `npm install`. I've added that small bit to my repo, feel free to reinclude again, thanks!

**Comment by ruyadorno** [comment]
cool! thanks for the heads up 😊 cleaned it up a little bit!

**Pull request merged**
